import { slugify } from "../curriculum";
import type { CurriculumWeek, LeetcodeDay, LeetcodeProblem } from "../types";

export const CONTENT_VERSION = 1;

function solve(name: string, pattern: string, url?: string): LeetcodeProblem {
  return { slug: slugify(name), name, pattern, role: "solve", ...(url !== undefined ? { url } : {}) };
}

function study(name: string, pattern: string, url?: string): LeetcodeProblem {
  return { slug: slugify(name), name, pattern, role: "study", ...(url !== undefined ? { url } : {}) };
}

function day(
  dayNumber: number,
  week: number,
  title: string,
  learn: string[],
  problems: LeetcodeProblem[],
  coldReview: string[] = [],
  prompt?: string,
): LeetcodeDay {
  return {
    dayId: `lc-d${String(dayNumber).padStart(2, "0")}`,
    day: dayNumber,
    week,
    title,
    learn,
    problems,
    coldReview,
    ...(prompt !== undefined ? { prompt } : {}),
  };
}

export const LEETCODE_WEEKS: CurriculumWeek[] = [
  {
    week: 1,
    title: "Arrays, Hashing & Two Pointers",
    intent: "The foundation — hash maps, frequency counting, and two-pointer reasoning.",
    firstDay: 1,
    lastDay: 7,
  },
  {
    week: 2,
    title: "Sliding Window, Stack & Binary Search",
    intent:
      "Sliding window, stack-based reasoning including monotonic stacks, and binary search — including searching a solution space, not just a sorted array.",
    firstDay: 8,
    lastDay: 14,
  },
  {
    week: 3,
    title: "Linked Lists + Trees",
    intent: "Pointer manipulation on linked lists, then tree fundamentals: DFS, BFS, and recursive thinking.",
    firstDay: 15,
    lastDay: 21,
  },
  {
    week: 4,
    title: "Heap, Backtracking & Graphs",
    intent: "This is where LeetCode starts feeling much more like real DSA — heaps, backtracking, and graph fundamentals.",
    firstDay: 22,
    lastDay: 28,
  },
  {
    week: 5,
    title: "Graphs, Intervals & Greedy",
    intent: "Topological sort, union find, interval sorting, and greedy reasoning.",
    firstDay: 29,
    lastDay: 35,
  },
  {
    week: 6,
    title: "Dynamic Programming",
    intent: "Recognizing overlapping subproblems, from 1-D DP through 2-D DP.",
    firstDay: 36,
    lastDay: 42,
  },
  {
    week: 7,
    title: "Mixed interview mode",
    intent:
      "Topic labels come off. Every day: one unseen medium (25 min max), one spaced-repetition problem from the review pile, and an optional third.",
    firstDay: 43,
    lastDay: 49,
  },
  {
    week: 8,
    title: "Actual interview preparation",
    intent:
      "Stop optimizing your LeetCode count. Now we test whether you can interview: timed mocks, your weakest topic, communication practice, and company-tagged problems.",
    firstDay: 50,
    lastDay: 56,
  },
];

export const LEETCODE_DAYS: LeetcodeDay[] = [
  day(
    1,
    1,
    "Complexity + Hash Maps",
    ["O(1), O(log n), O(n), O(n log n), O(n^2)", "arrays, sets, dictionaries"],
    [solve("Two Sum", "Hash Map"), solve("Contains Duplicate", "Hash Map")],
  ),
  day(
    2,
    1,
    "Frequency maps",
    ["Frequency map pattern: freq[x] = freq.get(x, 0) + 1 — this idea comes back constantly."],
    [solve("Valid Anagram", "Hash Map / Frequency Count"), solve("Group Anagrams", "Hash Map / Frequency Count")],
  ),
  day(
    3,
    1,
    "Hashing + Top K",
    [],
    [solve("Top K Frequent Elements", "Hash Map + Heap / Bucket Sort"), solve("Longest Consecutive Sequence", "Hash Set")],
  ),
  day(
    4,
    1,
    "Two pointers",
    ["Two pointers: L -> ... <- R"],
    [solve("Valid Palindrome", "Two Pointers"), solve("Two Sum II", "Two Pointers")],
  ),
  day(
    5,
    1,
    "Two-pointer reasoning",
    ["3Sum is the main problem today — don't rush it."],
    [solve("3Sum", "Two Pointers"), solve("Container With Most Water", "Two Pointers")],
  ),
  day(
    6,
    1,
    "Mixed review",
    ["Cold solve three problems, then one unseen easy/medium from Arrays."],
    [],
    ["two-sum", "group-anagrams", "3sum"],
  ),
  day(7, 1, "REST / review only", ["No new problems. Redo every red-rated problem."], [], []),
  day(
    8,
    2,
    "Fixed/variable window",
    ["Sliding window: L [ current valid window ] R — grow the window, move L when invalid."],
    [
      solve("Best Time to Buy and Sell Stock", "Sliding Window"),
      solve("Longest Substring Without Repeating Characters", "Sliding Window"),
    ],
  ),
  day(
    9,
    2,
    "Sliding window harder",
    ["Don't memorize the loops — understand what information the current window maintains."],
    [solve("Longest Repeating Character Replacement", "Sliding Window"), solve("Permutation in String", "Sliding Window")],
  ),
  day(
    10,
    2,
    "Stack",
    ["Learn when LIFO gives you something useful."],
    [solve("Valid Parentheses", "Stack"), solve("Min Stack", "Stack")],
  ),
  day(
    11,
    2,
    "Monotonic stack",
    ["Understand the monotonic-stack idea rather than the exact code."],
    [solve("Daily Temperatures", "Monotonic Stack"), solve("Car Fleet", "Monotonic Stack")],
  ),
  day(
    12,
    2,
    "Binary Search",
    ["You should be able to implement ordinary binary search almost automatically."],
    [solve("Binary Search", "Binary Search"), solve("Search a 2D Matrix", "Binary Search")],
  ),
  day(
    13,
    2,
    "Binary-search variants",
    ["Binary search isn't only \"find X in sorted array\" — it can search a solution space."],
    [solve("Koko Eating Bananas", "Binary Search on Answer"), solve("Find Minimum in Rotated Sorted Array", "Binary Search")],
  ),
  day(
    14,
    2,
    "Review",
    ["Then one unseen medium."],
    [],
    [
      "longest-substring-without-repeating-characters",
      "daily-temperatures",
      "koko-eating-bananas",
    ],
  ),
  day(
    15,
    3,
    "Linked list reversal + merging",
    ["prev <- curr -> next"],
    [solve("Reverse Linked List", "Linked List"), solve("Merge Two Sorted Lists", "Linked List")],
  ),
  day(
    16,
    3,
    "Fast & slow pointers",
    ["Fast/slow pointer technique."],
    [solve("Linked List Cycle", "Fast & Slow Pointers"), solve("Reorder List", "Fast & Slow Pointers")],
  ),
  day(
    17,
    3,
    "Linked list practice + LRU Cache",
    ["LRU Cache combines a Hash Map with a Doubly Linked List — don't worry if it's hard."],
    [solve("Remove Nth Node From End", "Linked List / Two Pointers"), study("LRU Cache", "Hash Map + Doubly Linked List")],
  ),
  day(
    18,
    3,
    "Tree fundamentals",
    ["node, root, leaf", "DFS", "BFS", "recursion"],
    [solve("Invert Binary Tree", "Trees / DFS"), solve("Maximum Depth of Binary Tree", "Trees / DFS")],
  ),
  day(
    19,
    3,
    "DFS",
    ["This is where recursive thinking starts becoming important."],
    [solve("Diameter of Binary Tree", "Trees / DFS"), solve("Balanced Binary Tree", "Trees / DFS")],
  ),
  day(
    20,
    3,
    "Tree structure",
    [],
    [
      solve("Same Tree", "Trees / DFS"),
      solve("Subtree of Another Tree", "Trees / DFS"),
      solve("Lowest Common Ancestor of BST", "Trees / BST"),
    ],
  ),
  day(
    21,
    3,
    "Tree review",
    ["Draw every tree before coding."],
    [],
    ["reverse-linked-list", "maximum-depth-of-binary-tree", "diameter-of-binary-tree", "lowest-common-ancestor-of-bst"],
  ),
  day(
    22,
    4,
    "Heap",
    ["import heapq", "min heap", "max-heap workaround", "Top K"],
    [solve("Kth Largest Element in a Stream", "Heap"), solve("K Closest Points to Origin", "Heap")],
  ),
  day(
    23,
    4,
    "Heap patterns",
    ["Median isn't mandatory to solve cold yet."],
    [solve("Kth Largest Element in an Array", "Heap"), study("Find Median From Data Stream", "Heap")],
  ),
  day(
    24,
    4,
    "Backtracking",
    ["choose -> explore -> undo"],
    [solve("Subsets", "Backtracking"), solve("Combination Sum", "Backtracking")],
  ),
  day(
    25,
    4,
    "More backtracking",
    ["Make recursion trees on paper."],
    [solve("Permutations", "Backtracking"), solve("Word Search", "Backtracking")],
  ),
  day(
    26,
    4,
    "Graph fundamentals",
    ["adjacency list", "DFS", "BFS", "visited set"],
    [solve("Number of Islands", "Graph DFS/BFS"), solve("Clone Graph", "Graph DFS/BFS")],
  ),
  day(
    27,
    4,
    "Graph BFS/DFS",
    ["Many \"grid\" problems are secretly graph problems."],
    [solve("Max Area of Island", "Graph DFS/BFS"), solve("Rotting Oranges", "Graph BFS")],
  ),
  day(
    28,
    4,
    "Review / mock",
    [],
    [],
    ["subsets", "number-of-islands", "rotting-oranges"],
    "45-minute mock: one unseen medium.",
  ),
  day(
    29,
    5,
    "Prerequisites / dependencies",
    ["Topological sort — shows up in prerequisites, dependency graphs, build systems, task scheduling."],
    [solve("Course Schedule", "Graph / Topological Sort"), solve("Course Schedule II", "Graph / Topological Sort")],
  ),
  day(
    30,
    5,
    "Union Find",
    ["Disjoint Set Union, conceptually. Don't over-invest yet."],
    [solve("Redundant Connection", "Union Find")],
  ),
  day(
    31,
    5,
    "Intervals",
    ["First rule: sort intervals. A surprising number of interval questions become straightforward afterward."],
    [solve("Insert Interval", "Intervals"), solve("Merge Intervals", "Intervals")],
  ),
  day(
    32,
    5,
    "More intervals",
    [],
    [solve("Non-overlapping Intervals", "Intervals"), solve("Meeting Rooms II", "Intervals")],
  ),
  day(
    33,
    5,
    "Greedy",
    ["Can I make the locally best decision without hurting the future?"],
    [solve("Maximum Subarray", "Greedy"), solve("Jump Game", "Greedy")],
  ),
  day(
    34,
    5,
    "Greedy harder",
    [],
    [solve("Gas Station", "Greedy"), solve("Partition Labels", "Greedy")],
  ),
  day(
    35,
    5,
    "Review",
    ["Mixed medium set, no topic labels — that's intentional."],
    [],
    ["course-schedule", "merge-intervals", "jump-game"],
  ),
  day(
    36,
    6,
    "1-D DP",
    ["Start recursive. Then memoize. Then convert to bottom-up.", "Core question: am I repeatedly solving the same smaller problem?"],
    [solve("Climbing Stairs", "1-D DP"), solve("Min Cost Climbing Stairs", "1-D DP")],
  ),
  day(
    37,
    6,
    "House Robber family",
    ["Very important DP family."],
    [solve("House Robber", "1-D DP"), solve("House Robber II", "1-D DP")],
  ),
  day(
    38,
    6,
    "Palindrome DP",
    [],
    [solve("Longest Palindromic Substring", "1-D DP"), solve("Palindromic Substrings", "1-D DP")],
  ),
  day(
    39,
    6,
    "Decode Ways + Coin Change",
    ["Coin Change is a major checkpoint."],
    [solve("Decode Ways", "1-D DP"), solve("Coin Change", "1-D DP")],
  ),
  day(
    40,
    6,
    "2-D DP introduction",
    ["Draw the matrix. Don't try to mentally simulate it."],
    [solve("Unique Paths", "2-D DP"), solve("Longest Common Subsequence", "2-D DP")],
  ),
  day(
    41,
    6,
    "Partition Equal Subset Sum + 0/1 Knapsack",
    ["This is where many seemingly unrelated DP questions start making sense."],
    [solve("Partition Equal Subset Sum", "2-D DP / Knapsack"), study("0/1 Knapsack", "2-D DP / Knapsack")],
  ),
  day(
    42,
    6,
    "DP review",
    ["Then explain the state transition verbally. No notes."],
    [],
    ["house-robber", "coin-change", "unique-paths"],
  ),
  day(
    43,
    7,
    "Random arrays/string medium",
    [],
    [],
    [],
    "Problem 1: unseen medium (arrays/strings), 25 minutes maximum. Problem 2: spaced-repetition problem from your red/yellow pile. Problem 3 (optional): only if you have energy.",
  ),
  day(
    44,
    7,
    "Random tree/graph medium",
    [],
    [],
    [],
    "Problem 1: unseen medium (tree/graph), 25 minutes maximum. Problem 2: spaced-repetition problem from your red/yellow pile. Problem 3 (optional): only if you have energy.",
  ),
  day(
    45,
    7,
    "Random heap/interval medium",
    [],
    [],
    [],
    "Problem 1: unseen medium (heap/interval), 25 minutes maximum. Problem 2: spaced-repetition problem from your red/yellow pile. Problem 3 (optional): only if you have energy.",
  ),
  day(
    46,
    7,
    "Random sliding-window/two-pointer medium",
    [],
    [],
    [],
    "Problem 1: unseen medium (sliding-window/two-pointer), 25 minutes maximum. Problem 2: spaced-repetition problem from your red/yellow pile. Problem 3 (optional): only if you have energy.",
  ),
  day(
    47,
    7,
    "Random DP medium",
    [],
    [],
    [],
    "Problem 1: unseen medium (DP), 25 minutes maximum. Problem 2: spaced-repetition problem from your red/yellow pile. Problem 3 (optional): only if you have energy.",
  ),
  day(48, 7, "Mock", [], [], [], "45-minute mock."),
  day(49, 7, "Review only", ["Review only."], [], []),
  day(50, 8, "Mock", [], [], [], "45 minutes. Talk while coding. No autocomplete dependence if possible."),
  day(
    51,
    8,
    "Weakest topic",
    [],
    [],
    [],
    "Look at your tracker and target today's problem at your weakest-rated pattern — not another random problem.",
  ),
  day(52, 8, "Two unseen mediums", [], [], [], "Two unseen mediums, 25 minutes each. No topic labels."),
  day(
    53,
    8,
    "Communication day",
    [],
    [],
    [],
    "Solve one medium, narrating explicitly: 1) clarify requirements, 2) examples, 3) brute force, 4) optimization, 5) code, 6) test, 7) time complexity, 8) space complexity. Record yourself if useful.",
  ),
  day(
    54,
    8,
    "Company-oriented practice",
    [],
    [],
    [],
    "Company-tagged -> recent -> medium. Only useful now that an interview may be coming up — don't spend eight weeks memorizing employer-specific lists.",
  ),
  day(55, 8, "Mock", [], [], [], "45 minutes. Unseen medium."),
  day(
    56,
    8,
    "Readiness test",
    [],
    [],
    [],
    "Three unseen mediums, 25-30 minutes each. Do not look at topics beforehand.",
  ),
];

export const LEETCODE_RESOURCES: Array<{ name: string; url?: string; note: string }> = [
  {
    name: "NeetCode 150",
    url: "https://neetcode.io/practice/practice/neetcode150",
    note: "Learn — your spine. 28 easy, 101 medium, 21 hard across the major interview patterns.",
  },
  {
    name: "NeetCode DSA for Beginners",
    url: "https://neetcode.io/courses/dsa-for-beginners/0",
    note: "DSA refresher for when something is genuinely unfamiliar — arrays, linked lists, recursion, sorting, binary search, trees, backtracking, heaps, hashing, graphs, DP, and bit manipulation.",
  },
  {
    name: "Tech Interview Handbook",
    url: "https://www.techinterviewhandbook.org/algorithms/study-cheatsheet/",
    note: "Reference / cheat sheets — use when you reach a topic and realize you don't actually understand it. Don't read the whole site beforehand.",
  },
  {
    name: "Grind 75",
    url: "https://www.techinterviewhandbook.org/grind75/about",
    note: "Alternate curated list / prioritization — tells you which problems deserve extra attention.",
  },
  {
    name: "LeetCode",
    note: "Actual coding — the practice platform and editorials.",
  },
];

export const LEETCODE_PATTERN_CLUES: Array<{ clue: string; pattern: string }> = [
  { clue: "Find pair/complement", pattern: "Hash map" },
  { clue: "Sorted array", pattern: "Two pointers / binary search" },
  { clue: "Contiguous substring", pattern: "Sliding window" },
  { clue: "Nested structures", pattern: "Stack" },
  { clue: "Top/lowest K", pattern: "Heap" },
  { clue: "Tree hierarchy", pattern: "DFS/BFS" },
  { clue: "Connected components", pattern: "Graph DFS/BFS" },
  { clue: "Dependencies", pattern: "Topological sort" },
  { clue: "Generate combinations", pattern: "Backtracking" },
  { clue: "Overlapping subproblems", pattern: "DP" },
  { clue: "Overlapping ranges", pattern: "Intervals" },
  { clue: "\"minimum possible X\"", pattern: "Binary search answer space" },
];
