import type { CurriculumWeek, SystemDesignDay } from "../types";

export const CONTENT_VERSION = 1;

const SOLVE_FIRST_CAUTION = "**Never look at the solution before attempting the problem.**";

export const SYSTEM_DESIGN_WEEKS: CurriculumWeek[] = [
  {
    week: 1,
    title: "Learn the language",
    intent:
      "Learn the vocabulary of system design — client/server, databases, caching, scaling, and consistency — so architecture descriptions stop sounding like a foreign language.",
    firstDay: 1,
    lastDay: 7,
  },
  {
    week: 2,
    title: "Learn your building blocks",
    intent:
      "Learn how the building blocks — queues, read/write scaling, realtime delivery, blob storage, search — combine, and review the reliability patterns that cut across all of them.",
    firstDay: 8,
    lastDay: 14,
  },
  {
    week: 3,
    title: "Classic interview problems",
    intent:
      "Switch from studying to solving: attempt each classic problem yourself before comparing against an expert solution, ending with a full 45-minute mock.",
    firstDay: 15,
    lastDay: 21,
  },
  {
    week: 4,
    title: "Become interview-ready",
    intent:
      "Combine everything learned so far on harder, more realistic problems, ending with a cold 45-minute final mock interview.",
    firstDay: 22,
    lastDay: 28,
  },
];

export const SYSTEM_DESIGN_DAYS: SystemDesignDay[] = [
  {
    dayId: "sd-d01",
    day: 1,
    week: 1,
    title: "What even is system design?",
    mode: "learn",
    learn: [
      "What system design interviews test",
      "Functional vs non-functional requirements",
      "What an HLD looks like",
      "Hello Interview Delivery Framework",
    ],
    exercise: "Design YouTube — produce only requirements. No architecture.",
    helloInterview: "Introduction → Delivery Framework",
  },
  {
    dayId: "sd-d02",
    day: 2,
    week: 1,
    title: "Networking + APIs",
    mode: "learn",
    learn: [
      "client/server",
      "request/response",
      "DNS",
      "HTTP/HTTPS",
      "REST",
      "RPC/gRPC",
      "TCP vs UDP — conceptually",
      "WebSockets",
    ],
    exercise:
      "Design APIs for posting a tweet, reading a tweet, following someone, and retrieving a feed. No distributed systems yet.",
    helloInterview: "Networking Essentials + API Design",
  },
  {
    dayId: "sd-d03",
    day: 3,
    week: 1,
    title: "Databases",
    mode: "learn",
    learn: [
      "relational DB",
      "tables",
      "primary keys",
      "indexes",
      "joins",
      "NoSQL",
      "document DB",
      "key-value DB",
      "SQL vs NoSQL",
    ],
    exercise:
      "Be able to answer: why wouldn't I just put everything in PostgreSQL? And why would PostgreSQL often be the right initial answer?",
    helloInterview: "Data Modeling + Database Indexing + PostgreSQL",
    alexXu: "Chapter 1 — Scale From Zero to Millions (optional)",
  },
  {
    dayId: "sd-d04",
    day: 4,
    week: 1,
    title: "Scaling servers",
    mode: "learn",
    learn: [
      "vertical scaling",
      "horizontal scaling",
      "stateless servers",
      "load balancing",
      "health checks",
      "reverse proxy",
      "API gateway",
    ],
    exercise:
      "Start with User → Server → Database, then scale it to User → Load Balancer → multiple Servers → Database. Understand why each box appeared.",
  },
  {
    dayId: "sd-d05",
    day: 5,
    week: 1,
    title: "Caching",
    mode: "learn",
    learn: [
      "what caching solves",
      "cache hit / miss",
      "Redis",
      "TTL",
      "cache-aside",
      "invalidation",
      "stale data",
      "CDN",
    ],
    helloInterview: "Caching + Redis",
  },
  {
    dayId: "sd-d06",
    day: 6,
    week: 1,
    title: "Replication + sharding",
    mode: "learn",
    learn: [
      "replicas",
      "read replicas",
      "horizontal partitioning",
      "shard keys",
      "hot shards",
      "consistent hashing",
    ],
    helloInterview: "Sharding + Consistent Hashing",
  },
  {
    dayId: "sd-d07",
    day: 7,
    week: 1,
    title: "Consistency + CAP + Week 1 review",
    mode: "learn",
    learn: [
      "strong consistency",
      "eventual consistency",
      "availability",
      "partition tolerance",
      "CAP",
      "durability",
      "latency",
    ],
    exercise:
      "Spend ~30 minutes drawing a basic Twitter-like service. No expert solution. This is your Week 1 checkpoint.",
  },
  {
    dayId: "sd-d08",
    day: 8,
    week: 2,
    title: "Message queues + async work",
    mode: "learn",
    learn: [
      "queue",
      "producer",
      "consumer",
      "Kafka",
      "asynchronous jobs",
      "retries",
      "dead-letter queue concept",
      "at-least-once processing",
      "idempotency",
    ],
    helloInterview: "Kafka + Managing Long Running Tasks",
  },
  {
    dayId: "sd-d09",
    day: 9,
    week: 2,
    title: "Scaling reads",
    mode: "learn",
    learn: ["indexes", "optimize queries", "denormalization where appropriate", "read replicas", "Redis", "CDN"],
    exercise:
      "Instagram suddenly has 100x more people viewing photos than uploading them. How do you scale reads?",
  },
  {
    dayId: "sd-d10",
    day: 10,
    week: 2,
    title: "Scaling writes",
    mode: "learn",
    learn: ["partitioning", "batching", "queues", "hot keys", "write contention", "load shedding"],
    exercise: "Don't memorize — ask: what exactly is failing when writes increase?",
    helloInterview: "Scaling Writes",
  },
  {
    dayId: "sd-d11",
    day: 11,
    week: 2,
    title: "Realtime systems",
    mode: "learn",
    learn: ["polling", "long polling", "Server-Sent Events", "WebSockets", "pub/sub"],
    exercise:
      "Which would you use for live stock prices, chat, email inbox, and delivery tracking? Explain why.",
  },
  {
    dayId: "sd-d12",
    day: 12,
    week: 2,
    title: "Files, images and video",
    mode: "learn",
    learn: [
      "blobs",
      "object storage",
      "S3-style storage",
      "CDN",
      "metadata vs file data",
      "chunked upload",
      "pre-signed URLs conceptually",
    ],
    helloInterview: "Handling Large Blobs",
  },
  {
    dayId: "sd-d13",
    day: 13,
    week: 2,
    title: "Search",
    mode: "learn",
    learn: [
      "database indexes vs search engine",
      "inverted indexes",
      "Elasticsearch",
      "autocomplete concept",
      "ranking at a high level",
    ],
    exercise: "Why shouldn't Yelp run LIKE '%pizza%' over a billion rows?",
  },
  {
    dayId: "sd-d14",
    day: 14,
    week: 2,
    title: "Reliability + patterns review",
    mode: "learn",
    learn: [
      "retries",
      "timeouts",
      "idempotency",
      "redundancy",
      "failover",
      "contention",
      "multi-step operations",
      "bottlenecks",
    ],
    exercise: "Spend 30 minutes answering: design a photo-sharing application. No solution.",
  },
  {
    dayId: "sd-d15",
    day: 15,
    week: 3,
    title: "URL Shortener",
    mode: "practice",
    learn: ["API", "database", "ID generation", "redirects", "cache", "read-heavy workload"],
    exercise: "Design Bitly.",
    helloInterview: "Bitly",
    alexXu: "Chapter 8",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d16",
    day: 16,
    week: 3,
    title: "Rate Limiter",
    mode: "practice",
    learn: ["token bucket", "sliding/fixed windows conceptually", "Redis", "distributed counters"],
    exercise: "Design a rate limiter: limit each user to 100 API requests/minute.",
    alexXu: "Chapter 4",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d17",
    day: 17,
    week: 3,
    title: "Notification System",
    mode: "practice",
    learn: [
      "event pipeline: event → queue → notification workers → APNs/FCM/SMS/email",
      "retrying without sending duplicate notifications",
    ],
    exercise: "Design a notification system: send push/email/SMS notifications to millions of users.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d18",
    day: 18,
    week: 3,
    title: "Chat / WhatsApp",
    mode: "practice",
    learn: [
      "WebSockets",
      "message IDs",
      "delivery state",
      "online/offline users",
      "queues",
      "persistence",
      "ordering",
    ],
    exercise: "Design WhatsApp-like messaging.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d19",
    day: 19,
    week: 3,
    title: "News Feed",
    mode: "practice",
    learn: [
      "fan-out on read (generate the feed when requested)",
      "fan-out on write (precompute feeds when content is created)",
    ],
    exercise: "Design a Twitter/Instagram feed.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d20",
    day: 20,
    week: 3,
    title: "Dropbox / Google Drive",
    mode: "practice",
    learn: ["blob/object storage", "metadata", "file chunking", "syncing", "deduplication conceptually", "CDN"],
    exercise: "Design Dropbox / Google Drive.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d21",
    day: 21,
    week: 3,
    title: "First full mock",
    mode: "practice",
    learn: [
      "requirements",
      "core entities",
      "API",
      "high-level design",
      "database choices",
      "scaling",
      "bottlenecks",
      "trade-offs",
      "communication",
    ],
    exercise:
      "Pick one problem randomly. Give yourself 45 minutes. Use a whiteboard / Excalidraw. Do not pause — talk continuously as though being interviewed, then score yourself on the concepts above. This is your Week 3 checkpoint.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d22",
    day: 22,
    week: 4,
    title: "Ticketmaster",
    mode: "practice",
    learn: ["contention", "reservation/hold", "locking", "transactions", "expiry", "consistency"],
    exercise:
      "Design concert ticket booking. Main concept: contention — two people want the same seat. What happens?",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d23",
    day: 23,
    week: 4,
    title: "YouTube",
    mode: "practice",
    learn: ["uploads", "object storage", "encoding workers", "queues", "CDN", "metadata", "recommendations can be out of scope"],
    exercise: "Design YouTube.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d24",
    day: 24,
    week: 4,
    title: "Uber / Yelp",
    mode: "practice",
    learn: ["location", "geospatial indexes", "nearby search", "realtime updates"],
    exercise: "Design Uber / Yelp. Don't get buried in geospatial math — you need the architectural idea.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d25",
    day: 25,
    week: 4,
    title: "Web Crawler",
    mode: "practice",
    learn: ["URL frontier", "fetcher", "parser", "deduplication", "storage", "new URL discovery"],
    exercise: "Design a web crawler.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d26",
    day: 26,
    week: 4,
    title: "Data-engineering design",
    mode: "practice",
    learn: [
      "ingestion pipeline: apps → Kafka → stream processors → data store → query/API → dashboard",
      "consumers falling behind",
      "partitioning",
      "duplicate handling",
      "late events",
      "hot vs cold storage",
    ],
    exercise:
      "Design a system that collects billions of application events and makes dashboards available within one minute.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d27",
    day: 27,
    week: 4,
    title: "AI-system design",
    mode: "practice",
    learn: [
      "RAG architecture: documents → ingestion → chunking → embeddings → vector DB",
      "query path: user → API → retrieval → reranker → LLM → response",
      "caching",
      "asynchronous ingestion",
      "model rate limits",
      "document updates",
      "latency",
      "retrieval quality",
      "observability",
      "failure handling",
    ],
    exercise: "Design a production RAG chatbot. Don't turn this into an ML-theory interview.",
    caution: SOLVE_FIRST_CAUTION,
  },
  {
    dayId: "sd-d28",
    day: 28,
    week: 4,
    title: "Final interview",
    mode: "practice",
    learn: [
      "requirements",
      "core entities",
      "API",
      "high-level design",
      "database choices",
      "scaling",
      "bottlenecks",
      "trade-offs",
      "communication",
    ],
    exercise:
      "No studying beforehand. Randomly choose from: URL shortener, notifications, WhatsApp, news feed, Ticketmaster, YouTube, Uber, crawler, metrics system. 45 minutes. Could you have this conversation with an engineer without needing notes?",
    caution: SOLVE_FIRST_CAUTION,
  },
];

export const SYSTEM_DESIGN_RESOURCES: Array<{ name: string; url?: string; note: string }> = [
  {
    name: "Hello Interview — System Design in a Hurry",
    url: "https://www.hellointerview.com/learn/system-design/in-a-hurry/introduction",
    note: "Primary — every day.",
  },
  {
    name: "Alex Xu, System Design Interview Vol. 1",
    note: "Book — use alongside relevant topics/problems, not read cover-to-cover.",
  },
  {
    name: "System Design Primer",
    url: "https://github.com/donnemartin/system-design-primer",
    note: "Reference — search it when something doesn't click.",
  },
  {
    name: "ByteByteGo",
    url: "https://bytebytego.com/courses/system-design-interview/foreword",
    note: "Visual explanations — use when you need a picture of a concept.",
  },
  {
    name: "Designing Data-Intensive Applications, 2nd Edition",
    url: "https://www.oreilly.com/library/view/designing-data-intensive-applications/9781098119058/",
    note: "Later — after you're interview-capable, for deeper engineering knowledge.",
  },
];
